name: 'Release'

on:
  push:
    tags:
      - '*'

env:
  BUF_USERNAME: vietanhduong

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Buf registry
        uses: docker/login-action@v1
        with:
          registry: plugins.buf.build
          username: ${{ env.BUF_USERNAME }}
          password: ${{ secrets.BUF_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            plugins.buf.build/${{ env.BUF_USERNAME }}/validate:${{ env.TAG }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Dockerfile
